SUMMARY = "RAUC update bundle for the Anthias image"
DESCRIPTION = "Signed A/B rootfs bundle. Install on a running device with \
    'rauc install anthias-bundle-<machine>.raucb' and reboot; U-Boot boots \
    the freshly written slot and rauc-mark-good confirms it."

inherit bundle

RAUC_BUNDLE_COMPATIBLE = "${MACHINE}"
RAUC_BUNDLE_VERSION = "${DISTRO_VERSION}-${DATETIME}"
RAUC_BUNDLE_VERSION[vardepsexclude] = "DATETIME"
RAUC_BUNDLE_DESCRIPTION = "Anthias OS ${DISTRO_VERSION} for ${MACHINE}"
RAUC_BUNDLE_FORMAT = "verity"

RAUC_BUNDLE_SLOTS = "rootfs"
RAUC_SLOT_rootfs = "anthias-image"
RAUC_SLOT_rootfs[fstype] = "ext4"

# Development PKI, generated by meta-anthias and committed on purpose so the
# OTA path is testable end to end out of the box. REPLACE BEFORE SHIPPING:
# point RAUC_KEY_FILE/RAUC_CERT_FILE at your production signing key and
# RAUC_KEYRING_FILE (recipes-core/rauc/files/ca.cert.pem) at its CA.
RAUC_KEY_FILE := "${THISDIR}/files/development-1.key.pem"
RAUC_CERT_FILE := "${THISDIR}/files/development-1.cert.pem"
